version: '3'
services:
  micro:
    container_name: tracker-shop
    image: snowplow/snowplow-micro:1.7.0
    volumes:
      - ./micro:/config
    restart: always
    ports:
      - "9090:9090"
    command: "--collector-config /config/micro.conf --iglu /config/iglu.json"
