version: '3'
services:
  micro:
    container_name: tracker-shop
    image: snowplow/snowplow-micro:2.0.0
    volumes:
      - ./micro:/config
      - ./my-enrichments:/config/enrichments
    ports:
      - "9090:9090"
    command: "--collector-config /config/micro.conf --iglu /config/iglu.json"
